// <auto-generated />
using System;
using KhanLogistics.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KhanLogistics.Migrations
{
    [DbContext(typeof(TransportMgmtContext))]
    [Migration("20260425094829_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("KhanLogistics.Models.BillTable", b =>
                {
                    b.Property<int>("BillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillID"), 1L, 1);

                    b.Property<double?>("ActualAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FID")
                        .HasColumnType("int");

                    b.Property<double?>("Gst")
                        .HasColumnType("float");

                    b.Property<DateTime?>("GstDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PId")
                        .HasColumnType("int");

                    b.Property<string>("PartyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PaymentReceived")
                        .HasColumnType("float");

                    b.Property<int?>("PaymentTablePId")
                        .HasColumnType("int");

                    b.Property<double?>("Tds")
                        .HasColumnType("float");

                    b.Property<double?>("TotalValue")
                        .HasColumnType("float");

                    b.HasKey("BillID");

                    b.HasIndex("PaymentTablePId");

                    b.ToTable("BillTables");
                });

            modelBuilder.Entity("KhanLogistics.Models.PaymentTable", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PId"), 1L, 1);

                    b.Property<string>("DocNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PayRecDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("Shortage")
                        .HasColumnType("float");

                    b.HasKey("PId");

                    b.ToTable("PaymentTables");
                });

            modelBuilder.Entity("KhanLogistics.Models.TblDispatch", b =>
                {
                    b.Property<int>("DispId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DispId"), 1L, 1);

                    b.Property<int?>("BillID")
                        .HasColumnType("int");

                    b.Property<string>("ChallanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DisVid")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DispatchQuantity")
                        .HasColumnType("float");

                    b.Property<double?>("FinalPrice")
                        .HasColumnType("float");

                    b.Property<bool?>("IsReceived")
                        .HasColumnType("bit");

                    b.Property<string>("Lr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Shortage")
                        .HasColumnType("int");

                    b.Property<double?>("TotalValue")
                        .HasColumnType("float");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DispId");

                    b.HasIndex("BillID");

                    b.ToTable("TblDispatches");
                });

            modelBuilder.Entity("KhanLogistics.Models.TblFactory", b =>
                {
                    b.Property<int>("FID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FID"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Gstin")
                        .HasColumnType("float");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("FID");

                    b.ToTable("TblFactories");
                });

            modelBuilder.Entity("KhanLogistics.Models.TblFreight", b =>
                {
                    b.Property<int>("DestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DestId"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FreightRate")
                        .HasColumnType("float");

                    b.Property<string>("Quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vid")
                        .HasColumnType("int");

                    b.Property<string>("Wheels")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DestId");

                    b.ToTable("TblFreights");
                });

            modelBuilder.Entity("KhanLogistics.Models.TblUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Doj")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastLogIn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("TblUsers");
                });

            modelBuilder.Entity("KhanLogistics.Models.TblVehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"), 1L, 1);

                    b.Property<DateTime?>("TaxEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TaxStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VehicleFitnessEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VehicleFitnessStartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VehicleInsurEndtDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VehicleInsurStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VehiclePermitDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VehicleType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleId");

                    b.ToTable("TblVehicles");
                });

            modelBuilder.Entity("KhanLogistics.Models.ViewModel.BillDetailViewModel", b =>
                {
                    b.Property<double?>("ActualAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BillQty")
                        .HasColumnType("float");

                    b.Property<string>("BillType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DispatchMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FID")
                        .HasColumnType("int");

                    b.Property<string>("FactoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Gst")
                        .HasColumnType("float");

                    b.Property<int?>("LrQty")
                        .HasColumnType("int");

                    b.Property<double?>("TaxableAmount")
                        .HasColumnType("float");

                    b.Property<double?>("Tds")
                        .HasColumnType("float");

                    b.ToTable("BillDetailViewModels");
                });

            modelBuilder.Entity("KhanLogistics.Models.ViewModel.Sp_QtyByDay", b =>
                {
                    b.Property<double?>("BillQty")
                        .HasColumnType("float");

                    b.Property<string>("DayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Factory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("totalQty")
                        .HasColumnType("float");

                    b.ToTable("Sp_QtyByDay");
                });

            modelBuilder.Entity("KhanLogistics.Models.ViewModel.Sp_QtyByMonth", b =>
                {
                    b.Property<double?>("Balance")
                        .HasColumnType("float");

                    b.Property<double?>("BillQty")
                        .HasColumnType("float");

                    b.Property<string>("Factory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("totalQty")
                        .HasColumnType("float");

                    b.ToTable("Sp_QtyByMonth");
                });

            modelBuilder.Entity("KhanLogistics.Models.ViewModel.SpBilldetail", b =>
                {
                    b.Property<double?>("ActualAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BillQty")
                        .HasColumnType("float");

                    b.Property<string>("BillType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DispatchMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FID")
                        .HasColumnType("int");

                    b.Property<string>("FactoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Gst")
                        .HasColumnType("float");

                    b.Property<int?>("LrQty")
                        .HasColumnType("int");

                    b.Property<double?>("TaxableAmount")
                        .HasColumnType("float");

                    b.Property<double?>("Tds")
                        .HasColumnType("float");

                    b.ToTable("SpBilldetails");
                });

            modelBuilder.Entity("KhanLogistics.Models.ViewModel.SpCheckBill", b =>
                {
                    b.Property<string>("BillNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChallanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DispatchQuantity")
                        .HasColumnType("float");

                    b.Property<string>("FactoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleNo")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SpCheckBill");
                });

            modelBuilder.Entity("KhanLogistics.Models.ViewModel.SpCheckPaymentDetails", b =>
                {
                    b.Property<double?>("ActualAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Deduction")
                        .HasColumnType("float");

                    b.Property<double?>("Gst")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PaymentReceived")
                        .HasColumnType("float");

                    b.Property<double?>("Tds")
                        .HasColumnType("float");

                    b.ToTable("SpCheckPaymentDetails");
                });

            modelBuilder.Entity("KhanLogistics.Models.ViewModel.SpExpoBilldetail", b =>
                {
                    b.Property<double?>("ActualAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BillQty")
                        .HasColumnType("float");

                    b.Property<string>("BillType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DispatchMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FactoryId")
                        .HasColumnType("int");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FinalPrice")
                        .HasColumnType("float");

                    b.Property<double?>("Gst")
                        .HasColumnType("float");

                    b.Property<int?>("LrQty")
                        .HasColumnType("int");

                    b.Property<double?>("TaxableAmount")
                        .HasColumnType("float");

                    b.Property<double?>("Tds")
                        .HasColumnType("float");

                    b.ToTable("SpExpoBilldetail");
                });

            modelBuilder.Entity("KhanLogistics.Models.ViewModel.SpGetDispatch", b =>
                {
                    b.Property<string>("BillNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChallanNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DispId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DispatchDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("DispatchQuantity")
                        .HasColumnType("float");

                    b.Property<string>("FactoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("UnitPrice")
                        .HasColumnType("float");

                    b.Property<string>("VehicleNo")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("SpGetDispatches");
                });

            modelBuilder.Entity("KhanLogistics.Models.ViewModel.SpOutStanding", b =>
                {
                    b.Property<double?>("ActualAmount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DispatchMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FactoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvoiceAge")
                        .HasColumnType("int");

                    b.Property<double?>("PaymentReceived")
                        .HasColumnType("float");

                    b.ToTable("SpOutStanding");
                });

            modelBuilder.Entity("KhanLogistics.Models.ViewModel.SpPaymentByDate", b =>
                {
                    b.Property<double?>("AmountAfterDeduction")
                        .HasColumnType("float");

                    b.Property<double?>("Deduction")
                        .HasColumnType("float");

                    b.Property<string>("FactoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Gst")
                        .HasColumnType("float");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Tds")
                        .HasColumnType("float");

                    b.Property<double?>("TotalActualAmount")
                        .HasColumnType("float");

                    b.Property<double?>("TotalPaymentReceived")
                        .HasColumnType("float");

                    b.ToTable("SpPaymentByDate");
                });

            modelBuilder.Entity("KhanLogistics.Models.BillTable", b =>
                {
                    b.HasOne("KhanLogistics.Models.PaymentTable", null)
                        .WithMany("tblBill")
                        .HasForeignKey("PaymentTablePId");
                });

            modelBuilder.Entity("KhanLogistics.Models.TblDispatch", b =>
                {
                    b.HasOne("KhanLogistics.Models.BillTable", "bill")
                        .WithMany("tblDispatches")
                        .HasForeignKey("BillID");

                    b.Navigation("bill");
                });

            modelBuilder.Entity("KhanLogistics.Models.BillTable", b =>
                {
                    b.Navigation("tblDispatches");
                });

            modelBuilder.Entity("KhanLogistics.Models.PaymentTable", b =>
                {
                    b.Navigation("tblBill");
                });
#pragma warning restore 612, 618
        }
    }
}
